### ISSUE TITLE
Two different PublicKey types?

### ISSUE THREAD

**Issue by gisenmann** [tel/saltine#19]
Hi!
More a question than a bug report: Is there a reason to have two different public (and secret) key types for box and sign? I think it would be ok, to use the same keypairs for both types for operations.
Am I wrong? Currently I convert between both via isEncoding, but that feels a little bit poor.
Götz

**Comment by tel** [comment]
Hi!

It's a very bad idea to mix these keys. They're not actually compatible as types at all. The base documentation is here

* http://nacl.cr.yp.to/sign.html
* http://nacl.cr.yp.to/box.html

which suggests that the keys aren't even necessarily the same length!
