### ISSUE TITLE
Better access for SecretKey/PublicKey/CombinedKey/Key/Nonce

### ISSUE THREAD

**Issue by tel** [tel/saltine#2]
Right now these are totally opaque boxes, which is a problem. Ideally it'd be nice to have a `lens`-like `IsByteString` class to project into them. Unfortunately, that can't quite work because `IsByteString` needs `Iso'`s. There's already a `Crypto.Saltine.Class` module containing `IsEncoding` which provides `Prism'` access to these guys.

This'll also lead to nice Show instances for these guys.

**Comment by linearray** [comment]
Did not touch or add anything lens-related, as I don't use it, but `Internal` modules do now expose all useful data types and provide `Show` instances.
