### ISSUE TITLE
Upload haddocks to Hackage

### ISSUE THREAD

**Issue by joachifm** [tel/saltine#21]
Hackage cannot build the package, so manually uploading the haddocks is necessary.
Not essential, I suppose, but nice nonetheless and lowers the barrier to entry, IMO.

**Comment by tel** [comment]
I've never done manual Hackage uploads. Is there a recommended process?

**Comment by joachifm** [comment]
I've never had occasion to do this either. Seems like something which should be a one-click operation, but it appears to be a bit more complicated than that. See [this post] by one of the Haddock maintainers. Neil Mitchel has [a script] to automate the process (one of many such scripts, it seems ...). I have no idea whether these posts still reflect current best practice.

Anyway, this is just something that would be nice to have and that I thought would be a quick fix, no need to expend too much time on it.

[this post]: http://fuuzetsu.co.uk/blog/posts/2014-01-06-Fix-your-Hackage-documentation.html
[a script]: http://neilmitchell.blogspot.ca/2014/10/fixing-haddock-docs-on-hackage.html

**Comment by tel** [comment]
Great! I'll take a look this weekend!



—

**Comment by lpeterse** [comment]
Using this script worked for me: https://gist.github.com/Fuuzetsu/8276421
```
hackagedocs saltine 0.0.0.3 username password
```
Taken from [this](http://fuuzetsu.co.uk/blog/posts/2014-01-06-Fix-your-Hackage-documentation.html) blog post by Fūzetsu.

**Comment by linearray** [comment]
Incidentally this was resolved yesterday.
