### ISSUE TITLE
Sealed boxes

### ISSUE THREAD

**Issue by linearray** [tel/saltine#24]
Hi,

I was wondering if there was any work done on adding support for sealed boxes, essentially boxes with encryption but not authentication, which were added in libsodium 1.0.3

If not, I'm going to give it a shot. Just wanted to make sure it's not already lying around somewhere.

**Comment by tel** [comment]
That definitely doesn't exist! I'm not able to currently continue pushing saltine forward very much, so contributions like this are definitely welcome!

**Comment by linearray** [comment]
In the Box module, is there a reason why you're not using the _easy variants of the respective libsodium functions (takes care of padding for you without introducing overhead)?

If I add this functionality saltine will require libsodium 1.0.3 or greater. Is that acceptable?

**Comment by tel** [comment]
The primary reason for both of these is probably just that this is a multi year old not frequently used project. If you're an active user and interested in maintainership I'm happy to talk about it :)

**Comment by linearray** [comment]
Merged.
