### ISSUE TITLE
Show instances

### ISSUE THREAD

**Issue by athanclark** [tel/saltine#26]
I'm building a simple session cache out of public keys and nonces, and it would be extremely useful if there were hashable instances for all the `ByteString`-convertable types, like `Nonce` `PublicKey` etc. I've just been building my own, out of newtypes and conversions, but I think these instances speak for themselves for how useful they could be. I may just implement it myself and submit a PR if that's okay :)

**Comment by athanclark** [comment]
I hate to be that person also, but is there any hope there could be a `Show` instance as well? Just for useful logging / exceptions

**Comment by athanclark** [comment]
Definitely, but on the same note, ByteStrings are _never_ really meaningful when shown, and it's really only useful for debugging purposes, but I digress :) I'll file a PR in a few hours! Thank you!

**Comment by linearray** [comment]
And a few short years later this is in master!
