### ISSUE TITLE
Fix hackage build

### ISSUE THREAD

**Issue by iphydf** [tel/saltine#29]
`All reported builds failed as of 2015-11-13 [all 5 reports]`

I would like to see this succeed. How do other libraries with FFI do this? My package http://hackage.haskell.org/package/hstox fails because saltine fails to build.

**Comment by linearray** [comment]
Sadly it is currently just not possible to automatically install extra-libraries on the hackage build server. You can however upload docs manually to hackage with `cabal upload -d`, which in turn does `cabal haddock --for-hackage`.

I did that for saltine just now and suggest you do it for your package as well.
