### ISSUE TITLE
SecretKey -> PublicKey function

### ISSUE THREAD

**Issue by athanclark** [tel/saltine#32]
I believe there is a method to which libsodum provides the ability to derive a secret key's associated public key - https://github.com/athanclark/purescript-crypt-nacl/blob/master/src/Crypt/NaCl/Box.purs#L34

But, I'm not sure if it's possible, given that this is just a "tweetnacl" implementation in javascript that's been wrapped.

**Comment by linearray** [comment]
That function is just an alias for crypto_scalarmult_base, for which there is already a binding.

It is my understanding that if you call this function with your secret key, you should get back the public key.
https://github.com/tel/saltine/blob/8d3837a027c35511e584c705e47b96f626a2a900/src/Crypto/Saltine/Core/ScalarMult.hs#L96

**Comment by linearray** [comment]
Customer seems to be happy with the proposed solution, closing.
