### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by hce** [tel/saltine#43]
Hi,

Any reason not to add this awesome package to the stackage repository?

Adding a package is easy; it is recommended that the maintainer of the library add the package to stackage themselves ( https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package ) but if you don't have time, I'd volunteer to take care of it.

Thanks
  HC

**Comment by linearray** [comment]
Adding to Stackage is fine, go ahead.

**Comment by bergey** [comment]
[Saltine is now in Stackage](https://www.stackage.org/package/saltine/snapshots).  Can this be closed?

**Comment by linearray** [comment]
Thanks.
