### ISSUE TITLE
Stronger types for detached signature interfaces

### ISSUE THREAD

**Issue by shlevy** [tel/saltine#50]
In my code I have:

```haskell
-- | A NaCl signature.
newtype Signature = Signature -- ctor not exported from public interface
  { -- | Extract the bytes of a 'Signature'. Guaranteed to be the
    -- right length.
    unSignature :: ByteString
  }

-- | Build a 'Signature'.
--
-- Can fail if the passed in bytes are not the right length.
makeSignature :: ByteString -> Maybe Signature
makeSignature b
  | BS.length b == NaClSizes.sign = Just (Signature b)
  | otherwise = Nothing
```

Would be nice to have something like this upstream and the relevant functions take a `Signature` instead of a `Bytestring`

**Comment by linearray** [comment]
I agree that most types should be wrapped in a `newtype` . I will start work on that for `1.0.0` as time permits, but certainly don't mind help on that front.

**Comment by linearray** [comment]
I've added a `Signature` type to the Sign and an `Authenticator` type to the SecretBox module.

Ideally I'd like to expand on that and add Plaintext, Ciphertext and sort of an AuthedPlaintext types in a useful way.

**Comment by linearray** [comment]
> Ideally I'd like to expand on that and add Plaintext, Ciphertext and sort of an AuthedPlaintext types in a useful way.

I thought on this some more and I think for the most part it's just busywork and doesn't add much safety.
