### ISSUE TITLE
Hashable instances for key types

### ISSUE THREAD

**Issue by shlevy** [tel/saltine#51]
Would be nice to be able to include public keys (and data structures containing them) in `HashSets`.

Or at least have an `Internal` module exporting the `*Key` constructors so that can be done by the user.

**Comment by linearray** [comment]
I think all relevant types do have `Hashable` instances?

They have been added here: https://github.com/tel/saltine/pull/49/files

**Comment by shlevy** [comment]
Unfortunately I don't remember the specifics here. Perhaps that PR wasn't in a release yet?
