### ISSUE TITLE
Support ChaCha20-Poly2105 IETF variant

### ISSUE THREAD

**Issue by ysangkok** [tel/saltine#52]
Libsodium now has support for this AEAD scheme specified originally in RFC7539 (superseded by [8439](https://tools.ietf.org/html/rfc8439) which is compatible AFAIK), which is now also implemented in Java and used in TLS 1.3.

Available in libsodium for three years: https://github.com/jedisct1/libsodium/commit/de451c23a0e53e2aa64f98eb04e0566245c696a1

It would be nice if there were bindings for it.

**Comment by linearray** [comment]
Fixed in master
