### ISSUE TITLE
Adding support for generichash (Blake2b)

### ISSUE THREAD

**Issue by donatello** [tel/saltine#54]
I would like to add `generichash` support to this library via binding to libsodium's `crypto_generichash` - would you be willing to review/give feedback on a pull request adding this binding? I am developing a haskell library for [Paseto tokens](https://paseto.io) and need a [binding to Blake2b](https://github.com/paragonie/paseto/blob/master/docs/01-Protocol-Versions/Version2.md#encrypt).

**Comment by linearray** [comment]
Thank you very much for the PR, I will take a look at this next week, once my workload has dropped to reasonable levels.

**Comment by donatello** [comment]
@linearray Friendly reminder to please take a look at the pull request.

**Comment by linearray** [comment]
Sorry for the delay, I promise I'll get to it today.

**Comment by linearray** [comment]
Merged.
