### ISSUE TITLE
Please allow newer `profunctors`

### ISSUE THREAD

**Issue by ezzieyguywuf** [tel/saltine#57]
I have succesfully built this using `ghc-8.10.3` and `profunctors-5.6.1`.

If you are able to make this change and release a new version, it will allow us to better package this project in gentoo.

**Comment by linearray** [comment]
Done in 0.1.1.1

**Comment by ezzieyguywuf** [comment]
Great, thank you, I have updated our package in gentoo with [this commit][1] 👍 

[1]: https://github.com/gentoo-haskell/gentoo-haskell/commit/2df9ca570104552add29db388a4776a855448229
