### ISSUE TITLE
Thread safety for random functions.

### ISSUE THREAD

**Issue by tel** [tel/saltine#7]
The random generation functions are not threadsafe, so it's unclear what their behavior will be in concurrent settings.
- `randombytes_random`
- `randombytes_uniform`
- `randombytes_buf`
- `randombytes_close`
- `crypto_sign_keypair`, and
- `crypto_box_keypair`

**Comment by TomMD** [comment]
Is this still accurate?  I [read](https://download.libsodium.org/doc/usage/):

```
sodium_init() initializes the library and should be called before any other function provided by Sodium.
The function can be called more than once, and can be called simultaneously from multiple threads since version 1.0.11.
After this function returns, all of the other functions provided by Sodium will be thread-safe.
```

**Comment by linearray** [comment]
Yep, this is quite outdated. All functions are thread-safe nowadays.
